-- Migration 002
-- Popula a tabela cardapio com os produtos e preços iniciais do sistema.
-- Data: 2026-01-28

insert into cardapio (categoria, nome, preco, descricao) values
('Lanches', 'Hambúrguer', 21.00, 'pao de hamburguer, tomate, maionese e hamburguer'),
('Lanches', 'Calabresa', 26.00, 'pao frances, tomate e calabresa'),
('Lanches', 'X-Calabresa', 28.00, 'pao frances, tomate, cebola, calabresa e mussarela'),
('Lanches', 'Combinado', 22.50, 'pao de hamburguer, milho, catupiry e mussarela'),
('Lanches', 'X-Burguer', 24.50, 'pao de hamburguer, tomate, maionese, hamburguer e mussarela'),
('Lanches', 'X-Salada', 25.50, 'pao de hamburguer, tomate, maionese, alface, hamburguer e mussarela'),
('Lanches', 'Misto', 25.50, 'pao, tres fatias de presunto e tres fatias de mussarela'),
('Lanches', 'Especial', 29.50, 'pao, tomate, maionese, hamburguer, presunto e mussarela'),
('Lanches', 'X-Egg', 29.50, 'pao, tomate, maionese, hamburguer, ovo e mussarela'),
('Lanches', 'Prensado', 29.50, 'pao, tomate, maionese, presunto e mussarela'),
('Lanches', 'Quaresma', 29.50, 'pao, tomate, maionese, alface, batata palha, ovo, milho e mussarela'),
('Lanches', 'Americano', 29.50, 'pao, tomate, maionese, alface, ovo, presunto e mussarela'),
('Lanches', 'Bacon', 32.50, 'pao, tomate, maionese, hamburguer, bacon e mussarela'),
('Lanches', 'Baita Burgue', 32.50, 'pao, tomate, maionese, hamburguer, ovo, presunto e mussarela'),
('Lanches', 'Ki-lanche', 38.00, 'pao, tomate, maionese, dois hamburgueres, ovo, presunto e mussarela'),
('Lanches', 'Baita Bacon', 35.50, 'pao, tomate, maionese, hamburguer, bacon, ovo, presunto e mussarela'),
('Lanches', 'Galinhao', 35.50, 'pao, tomate, maionese, frango desfiado, milho e mussarela'),
('Lanches', 'X-frango', 35.50, 'pao, tomate, maionese, file de frango, milho e mussarela'),
('Lanches', 'Mineiro', 37.50, 'pao, tomate, maionese, hamburguer, frango, ovo, bacon, presunto e mussarela'),
('Lanches', 'Churrasco', 37.50, 'pao, tomate, pernil, cebola e mussarela'),
('Lanches', 'XR', 41.00, 'pao, tomate, alface, maionese, dois hamburgueres, batata palha, milho, cebola roxa e mussarela'),
('Lanches', 'Nissan', 37.00, 'pao, tomate, maionese, batata, frango, milho e catupiry'),
('Lanches', 'Tropical', 41.50, 'pao, tomate, pernil, batata, cebola, abacaxi e mussarela'),
('Lanches', 'Carijo', 37.00, 'pao, tomate, maionese, batata, frango, catupiry, presunto e mussarela'),
('Lanches', 'X-Tudo', 39.50, 'pao, tomate, maionese, alface, hamburguer, bacon, ovo, frango, milho, presunto e mussarela'),
('Lanches', 'Carioca', 37.50, 'pao, tomate, maionese, hamburguer, bacon, cheddar, ovo, milho, batata e mussarela'),
('Lanches', 'Mineirão', 55.00, 'pao, tomate, maionese, dois hamburgueres, frango, bacon, catupiry, milho, presunto, mussarela e batata'),
('Lanches', 'Frango no Prato', 41.50, 'alface, tomate, batata, file de frango, bacon, milho e mussarela'),
('Lanches', 'Pernil no prato', 41.50, 'alface, tomate, batata, pernil, cebola, bacon e mussarela'),
('Lanches', 'Churrasco de Contra File', 55.00, 'pao frances, tomate, cebola, contra-file e mussarela'),

('Macarrão', 'Calabresa', 22.00, 'macarrao, milho, bacon, cebola, molho e mussarela'),
('Macarrão', 'Pernil', 24.00, 'macarrao, milho, bacon, cebola, molho e mussarela'),
('Macarrão', 'Frango', 24.00, 'macarrao, milho, bacon, cebola, molho e mussarela'),
('Macarrão', 'Bolonhesa', 23.00, 'macarrao, hamburguer, molho, cebola, milho e mussarela'),

('Porções', 'Batata simples', 24.00, NULL),
('Porções', 'Batata c/ queijo e bacon', 38.50, NULL),
('Porções', 'Calabresa e cebola', 41.00, NULL),
('Porções', 'Pernil e cebola', 55.00, NULL),
('Porções', 'Contra-filé', 90.00, NULL),

('Omeletes', 'Da Casa', 23.00, 'quatro ovos, presunto, queijo, batata, milho e cebola'),
('Omeletes', 'Catupiry', 26.00, 'quatro ovos, catupiry, milho, bacon, presunto, queijo, batata e cebola'),
('Omeletes', 'Cheddar', 26.00, 'quatro ovos, cheddar, milho, bacon, presunto, queijo, batata e cebola'),
('Omeletes', 'Frango', 27.00, 'quatro ovos, frango, milho, bacon, presunto, queijo, batata e cebola'),

('Bebidas', 'Coquinha 200ml', 4.00, NULL),
('Bebidas', 'Coca lata sabores', 7.00, NULL),
('Bebidas', 'Del Vale lata sabores', 7.00, NULL),
('Bebidas', 'H2O sabores', 7.50, NULL),
('Bebidas', 'Coca 600ml', 10.00, NULL),
('Bebidas', 'Guaraná Antártica 1L', 10.00, NULL),
('Bebidas', 'Coca 2L sabores', 17.00, NULL),
('Bebidas', 'Laranja copo', 10.00, NULL),
('Bebidas', 'Laranja jarra', 20.00, NULL),
('Bebidas', 'Acerola', 12.00, NULL),
('Bebidas', 'Abacaxi', 12.00, NULL),
('Bebidas', 'Abacaxi c/ limão', 12.00, NULL),
('Bebidas', 'Manga', 12.00, NULL),
('Bebidas', 'Maracuja', 12.00, NULL),

('Cervejas', 'Brahma lata', 7.00, NULL),
('Cervejas', 'Skol lata', 7.00, NULL),
('Cervejas', 'Skol litrinho', 7.00, NULL),
('Cervejas', 'Heineken', 12.00, NULL),
('Cervejas', 'Água com gás', 4.50, NULL),
('Cervejas', 'Água sem gás', 4.00, NULL),

('Doces', 'Bombom caseiro', 6.00, NULL);