-- Popula a tabela ingredientes_indisponiveis_dia com todos os ingredientes padronizados (MAIÚSCULAS, sem acentos)
-- Ajuste a coluna pg conforme sua regra de "paga na troca"
INSERT INTO ingredientes_indisponiveis_dia ( ingrediente, indisponivel, pg)
VALUES
  (1, 'PAO DE HAMBURGUER', true, true),
  (1, 'PAO FRANCES', true, true),
  (1, 'TOMATE', true, true),
  (1, 'MAIONESE', true, true),
  (1, 'HAMBURGUER', true, true),
  (1, 'MILHO', true, true),
  (1, 'BACON', true, true),
  (1, 'CALABRESA', true, true),
  (1, 'MUSSARELA', true, true),
  (1, 'PERNIL', true, true),
  (1, 'PRESUNTO', true, true),
  (1, 'FRANGO FILE', true, true),
  (1, 'FRANGO DESFIADO', true, true),
  (1, 'OVO', true, true),
  (1, 'CEBOLA', true, true),
  (1, 'BATATA PALHA', true, true),
  (1, 'ALFACE', true, true),
  (1, 'CATUPIRY', true, true),
  (1, 'CHEDDAR', true, true),
  (1, 'ABACAXI', true, true),
  (1, 'CONTRA FILE', true, true),
  (1, 'BATATA FRITA', true, true),
  (1, 'COQUINHA 200ML', true, true),
  (1, 'COCA LATA', true, true),
  (1, 'DEL VALLE LATA', true, true),
  (1, 'H2O', true, true),
  (1, 'COCA 600ML', true, true),
  (1, 'GUARANA ANTARTICA 1LITRO', true, true),
  (1, 'COCA 2L', true, true),
  (1, 'SUCO LARANJA COPO', true, true),
  (1, 'SUCO LARANJA JARRA', true, true),
  (1, 'BRAHMA LATA', true, true),
  (1, 'SKOL LATA', true, true),
  (1, 'SKOL LITRINHO', true, true),
  (1, 'BRAHMA LITRINHO', true, true),
  (1, 'HEINEKEN', true, true),
  (1, 'AGUA', true, true),
  (1, 'AGUA COM GAS', true, true),
  (1, 'AGUA SEM GAS', true, true),
  (1, 'BOMBOM', true, true)
ON CONFLICT (ingrediente) DO NOTHING;